/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "algebra-step-checker",
  "name": "Step Check",
  "supabaseUrl": "",
  "supabaseAnonKey": "",
  "aiProxy": "",
  "google": false,
  "prompts": [
    {
      "say": "Check my work on this equation",
      "does": "Verifies each line and finds the first error."
    },
    {
      "say": "Show me a worked solution to 2x^2 - 3x + 1 = 0",
      "does": "Solves it step by step, with each step verified."
    },
    {
      "say": "Give me five problems on my weakest mistake",
      "does": "Starts a practice set aimed at that misconception."
    }
  ]
};
